spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/memories
logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"
server:
  port: 8080